---
- setup: 
- import_tasks: apt_cacher_ng.yml
- import_tasks: packages.yml
- import_tasks: hostname.yml
- import_tasks: kernel.yml
- import_tasks: tuning.yml
- import_tasks: reboot.yml
- import_tasks: sshd.yml
- import_tasks: user.yml
